/// 内置 RSS 源目录（来源 legacy/src/utils/feeds.js，6 轮可达性实测，共 86 个）。
/// DEFAULT_FEEDS 首次启动订阅；FEEDS 供「按分类选择订阅源」面板；CATEGORIES 驱动分类导航。
class FeedDef {
  final String title;
  final String url;
  final String category;
  const FeedDef(this.title, this.url, this.category);
}

const List<(String key, String label)> categories = [
  ('News', '新闻'),
  ('Science', '科学'),
  ('Health', '健康'),
  ('Tech', '科技'),
  ('Business', '商业'),
  ('Environment', '环境'),
  ('Food', '食物'),
  ('Art', '艺术'),
  ('Design', '设计'),
  ('Books', '书籍文学'),
  ('Ideas', '思想文化'),
  ('Learner', '英语学习'),
  ('Sports', '体育'),
  ('Travel', '旅行'),
  ('Education', '教育'),
  ('Policy', '政策智库'),
  ('Life', '生活'),
];

const List<FeedDef> feedCatalog = [
  FeedDef('NPR News', 'https://feeds.npr.org/1001/rss.xml', 'News'),
  FeedDef('NPR World', 'https://feeds.npr.org/1004/rss.xml', 'News'),
  FeedDef('France24 English', 'https://www.france24.com/en/rss', 'News'),
  FeedDef('Sky News World', 'https://feeds.skynews.com/feeds/rss/world.xml', 'News'),
  FeedDef('CNBC Top', 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114', 'News'),
  FeedDef('The Hill', 'https://thehill.com/feed/', 'News'),
  FeedDef('The 19th', 'https://19thnews.org/feed/', 'News'),
  FeedDef('Nature', 'https://www.nature.com/nature.rss', 'Science'),
  FeedDef('Quanta', 'https://www.quantamagazine.org/feed/', 'Science'),
  FeedDef('NPR Science', 'https://feeds.npr.org/1019/rss.xml', 'Science'),
  FeedDef('Space.com', 'https://www.space.com/feeds/all', 'Science'),
  FeedDef('Live Science', 'https://www.livescience.com/feeds/all', 'Science'),
  FeedDef('Popular Science', 'https://www.popsci.com/feed/', 'Science'),
  FeedDef('Science Daily', 'https://www.sciencedaily.com/rss/all.xml', 'Science'),
  FeedDef('Hakai Magazine', 'https://hakaimagazine.com/feed/', 'Science'),
  FeedDef('Undark', 'https://undark.org/feed/', 'Science'),
  FeedDef('Anthropocene', 'https://www.anthropocenemagazine.org/feed/', 'Science'),
  FeedDef('Nautilus', 'https://nautil.us/feed/', 'Science'),
  FeedDef('Asimov Press', 'https://www.asimov.press/feed', 'Science'),
  FeedDef('NPR Health', 'https://feeds.npr.org/1025/rss.xml', 'Health'),
  FeedDef('STAT', 'https://www.statnews.com/feed/', 'Health'),
  FeedDef('The Verge', 'https://www.theverge.com/rss/index.xml', 'Tech'),
  FeedDef('Ars Technica', 'http://feeds.arstechnica.com/arstechnica/index', 'Tech'),
  FeedDef('Wired', 'https://www.wired.com/feed/rss', 'Tech'),
  FeedDef('Hacker News', 'https://hnrss.org/frontpage', 'Tech'),
  FeedDef('Engadget', 'https://www.engadget.com/rss.xml', 'Tech'),
  FeedDef('MIT Tech Review', 'https://www.technologyreview.com/feed/', 'Tech'),
  FeedDef('TechCrunch', 'https://techcrunch.com/feed/', 'Tech'),
  FeedDef('Dev.to', 'https://dev.to/feed', 'Tech'),
  FeedDef('freeCodeCamp', 'https://www.freecodecamp.org/news/rss/', 'Tech'),
  FeedDef('HackerNoon', 'https://hackernoon.com/feed', 'Tech'),
  FeedDef('InfoQ', 'https://feed.infoq.com/', 'Tech'),
  FeedDef('Stratechery', 'https://stratechery.com/feed/', 'Tech'),
  FeedDef('Fortune', 'https://fortune.com/feed', 'Business'),
  FeedDef('Grist', 'https://grist.org/feed/', 'Environment'),
  FeedDef('Eater', 'https://www.eater.com/rss/index.xml', 'Food'),
  FeedDef('Bon Appétit', 'https://www.bonappetit.com/feed/rss', 'Food'),
  FeedDef('Hyperallergic', 'https://hyperallergic.com/feed/', 'Art'),
  FeedDef('Colossal', 'https://www.thisiscolossal.com/feed/', 'Art'),
  FeedDef('Smashing Magazine', 'https://www.smashingmagazine.com/feed/', 'Design'),
  FeedDef('NPR Books', 'https://feeds.npr.org/1032/rss.xml', 'Books'),
  FeedDef('Literary Hub', 'https://lithub.com/feed/', 'Books'),
  FeedDef('Longreads', 'https://longreads.com/feed/', 'Books'),
  FeedDef('Brain Pickings', 'https://www.brainpickings.org/feed/', 'Books'),
  FeedDef('Wait But Why', 'https://waitbutwhy.com/feed', 'Books'),
  FeedDef('Electric Literature', 'https://electricliterature.com/feed/', 'Books'),
  FeedDef('Book Riot', 'https://bookriot.com/feed/', 'Books'),
  FeedDef('The Paris Review', 'https://www.theparisreview.org/blog/feed/', 'Books'),
  FeedDef('Arts & Letters Daily', 'https://aldaily.com/feed/', 'Books'),
  FeedDef('NPR TED', 'https://feeds.npr.org/1054/rss.xml', 'Ideas'),
  FeedDef('TED Blog', 'https://blog.ted.com/feed/', 'Ideas'),
  FeedDef('TED Ideas', 'https://ideas.ted.com/feed/', 'Ideas'),
  FeedDef('The Browser', 'https://thebrowser.com/feed/', 'Ideas'),
  FeedDef('Aeon', 'https://aeon.co/feed', 'Ideas'),
  FeedDef('Psyche', 'https://psyche.co/feed', 'Ideas'),
  FeedDef('3 Quarks Daily', 'https://3quarksdaily.com/feed/', 'Ideas'),
  FeedDef('Farnam Street', 'https://fs.blog/feed/', 'Ideas'),
  FeedDef('Freakonomics', 'https://freakonomics.com/feed/', 'Ideas'),
  FeedDef('Works in Progress', 'https://www.worksinprogress.news/feed', 'Ideas'),
  FeedDef('Mental Floss', 'https://www.mentalfloss.com/feed', 'Ideas'),
  FeedDef('JSTOR Daily', 'https://daily.jstor.org/feed/', 'Ideas'),
  FeedDef('HistoryExtra', 'https://www.historyextra.com/feed/', 'Ideas'),
  FeedDef('Nieman Lab', 'https://www.niemanlab.org/feed/', 'Ideas'),
  FeedDef('Our World in Data', 'https://ourworldindata.org/feed', 'Ideas'),
  FeedDef('News in Levels', 'https://www.newsinlevels.com/feed/', 'Learner'),
  FeedDef('Grammarly Blog', 'https://www.grammarly.com/blog/feed/', 'Learner'),
  FeedDef('Open Culture', 'https://www.openculture.com/feed', 'Learner'),
  FeedDef('Daily Writing Tips', 'https://www.dailywritingtips.com/feed/', 'Learner'),
  FeedDef('Writing Excuses', 'https://writingexcuses.com/feed/', 'Learner'),
  FeedDef('Espresso English', 'https://www.espressoenglish.net/feed/', 'Learner'),
  FeedDef('engVid', 'https://www.engvid.com/feed/', 'Learner'),
  FeedDef('FluentU Blog', 'https://www.fluentu.com/blog/english/feed/', 'Learner'),
  FeedDef('A Way with Words', 'https://www.awaywithwords.com/feed/', 'Learner'),
  FeedDef('Sky Sports', 'https://www.skysports.com/rss/12040', 'Sports'),
  FeedDef('SB Nation', 'https://www.sbnation.com/rss/index.xml', 'Sports'),
  FeedDef('CyclingTips', 'https://www.cyclingtips.com/feed/', 'Sports'),
  FeedDef('Skift', 'https://skift.com/feed/', 'Travel'),
  FeedDef('Matador Network', 'https://matadornetwork.com/feed/', 'Travel'),
  FeedDef('Inside Higher Ed', 'https://www.insidehighered.com/rss.xml', 'Education'),
  FeedDef('The Hechinger Report', 'https://hechingerreport.org/feed/', 'Education'),
  FeedDef('Higher Ed Dive', 'https://www.highereddive.com/feeds/news/', 'Education'),
  FeedDef('KQED MindShift', 'https://ww2.kqed.org/mindshift/feed/', 'Education'),
  FeedDef('TeachThought', 'https://www.teachthought.com/feed/', 'Education'),
  FeedDef('Bruegel', 'https://www.bruegel.org/rss.xml', 'Policy'),
  FeedDef('Aspen Institute', 'https://www.aspeninstitute.org/feed/', 'Policy'),
  FeedDef('Lifehacker', 'https://lifehacker.com/rss', 'Life'),
];

const List<FeedDef> defaultFeeds = [
  FeedDef('NPR News', 'https://feeds.npr.org/1001/rss.xml', 'News'),
  FeedDef('France24 English', 'https://www.france24.com/en/rss', 'News'),
  FeedDef('Nature', 'https://www.nature.com/nature.rss', 'Science'),
  FeedDef('Quanta', 'https://www.quantamagazine.org/feed/', 'Science'),
  FeedDef('The Verge', 'https://www.theverge.com/rss/index.xml', 'Tech'),
  FeedDef('Ars Technica', 'http://feeds.arstechnica.com/arstechnica/index', 'Tech'),
  FeedDef('Hacker News', 'https://hnrss.org/frontpage', 'Tech'),
  FeedDef('Literary Hub', 'https://lithub.com/feed/', 'Books'),
  FeedDef('Wait But Why', 'https://waitbutwhy.com/feed', 'Books'),
  FeedDef('Aeon', 'https://aeon.co/feed', 'Ideas'),
  FeedDef('Psyche', 'https://psyche.co/feed', 'Ideas'),
  FeedDef('News in Levels', 'https://www.newsinlevels.com/feed/', 'Learner'),
  FeedDef('Espresso English', 'https://www.espressoenglish.net/feed/', 'Learner'),
  FeedDef('Fortune', 'https://fortune.com/feed', 'Business'),
  FeedDef('Lifehacker', 'https://lifehacker.com/rss', 'Life'),
];

String? categoryLabel(String key) {
  for (final c in categories) {
    if (c.$1 == key) return c.$2;
  }
  return null;
}
