// 内置 RSS 源（21 个，中国大陆实测可达）
export const BUILTIN_FEEDS = [
  { title: 'NPR News', url: 'https://feeds.npr.org/1001/rss.xml', category: 'News' },
  { title: 'NPR Books', url: 'https://feeds.npr.org/1032/rss.xml', category: 'Books' },
  { title: 'NPR TED', url: 'https://feeds.npr.org/1054/rss.xml', category: 'Ideas' },
  { title: 'France24 English', url: 'https://www.france24.com/en/rss', category: 'News' },
  { title: 'Sky News World', url: 'https://feeds.skynews.com/feeds/rss/world.xml', category: 'News' },
  { title: 'CNBC Top', url: 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114', category: 'Business' },
  { title: 'Scientific American', url: 'https://www.scientificamerican.com/feed/', category: 'Science' },
  { title: 'Nature', url: 'https://www.nature.com/nature.rss', category: 'Science' },
  { title: 'Quanta', url: 'https://www.quantamagazine.org/feed/', category: 'Science' },
  { title: 'New Scientist', url: 'https://www.newscientist.com/feed/', category: 'Science' },
  { title: 'The Verge', url: 'https://www.theverge.com/rss/index.xml', category: 'Tech' },
  { title: 'Ars Technica', url: 'http://feeds.arstechnica.com/arstechnica/index', category: 'Tech' },
  { title: 'Wired', url: 'https://www.wired.com/feed/rss', category: 'Tech' },
  { title: 'Hacker News', url: 'https://hnrss.org/frontpage', category: 'Tech' },
  { title: 'Engadget', url: 'https://www.engadget.com/rss.xml', category: 'Tech' },
  { title: 'MIT Tech Review', url: 'https://www.technologyreview.com/feed/', category: 'Tech' },
  { title: 'Smashing Magazine', url: 'https://www.smashingmagazine.com/feed/', category: 'Design' },
  { title: 'Literary Hub', url: 'https://lithub.com/feed/', category: 'Books' },
  { title: 'Wait But Why', url: 'https://waitbutwhy.com/feed', category: 'Ideas' },
  { title: 'Lifehacker', url: 'https://lifehacker.com/rss', category: 'Life' },
  { title: 'Aeon', url: 'https://aeon.co/feed', category: 'Ideas' },
  { title: 'Psyche', url: 'https://psyche.co/feed', category: 'Ideas' },
  { title: 'Nautilus', url: 'https://nautil.us/feed/', category: 'Science' },
  { title: 'Longreads', url: 'https://longreads.com/feed/', category: 'Literature' },
  { title: 'Brain Pickings', url: 'https://www.brainpickings.org/feed/', category: 'Books' },
  { title: 'Stratechery', url: 'https://stratechery.com/feed/', category: 'Tech' },
]

